USE DATABASE SALESFORCE_DEMO_DB;
USE SCHEMA public;
CREATE OR REPLACE NETWORK RULE agent_net_rule
  TYPE = IPV4
  MODE = INGRESS 
  VALUE_LIST = ('0.0.0.0')
  COMMENT ='cloud egress ip range';

  CREATE  NETWORK POLICY IF NOT EXISTS agent_net_policy 
  allowed_network_rule_list = ('AGENT_NET_RULE');

  CREATE OR ALTER AUTHENTICATION POLICY my_agentforce_policy
  PAT_POLICY=(
    MAX_EXPIRY_IN_DAYS = 30
    NETWORK_POLICY_EVALUATION = NOT_ENFORCED 
  );

ALTER USER IF EXISTS dc_user ADD PROGRAMMATIC ACCESS TOKEN agentforce_token 
SET MINS_TO_BYPASS_NETWORK_POLICY_REQUIREMENT = 1440;

SHOW USER PATS FOR USER dc_user;